
ogbn-arxiv:
  lr: 0.001 
  lr_f: 0.005  
  num_hidden: 1024
  num_heads: 4  #4
  weight_decay: 0.06
  weight_decay_f: 1e-4   
  max_epoch: 40
  max_epoch_f: 1000
  batch_size: 512  
  batch_size_f: 256
  num_layers: 4
  encoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 1024 
  drop_edge_rate:  0.5 
  drop_feature_rate_1: 0.0 
  drop_feature_rate_2: 0.0 
  tau: 0.5
  

ogbn-products:
  lr: 0.001 
  lr_f: 0.001  
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 1e-4  
  max_epoch: 8 
  max_epoch_f: 1000
  batch_size: 512 
  batch_size_f: 256
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 1024  
  drop_edge_rate:  0.5 
  drop_feature_rate_1: 0.5 
  drop_feature_rate_2: 0.5 
  tau: 0.5

ogbn-papers100M:  
  lr: 0.001   
  lr_f: 0.001  
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 0.04  
  weight_decay_f: 0  #org 0
  max_epoch: 10 # 
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 256
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 1024 
  drop_edge_rate:  0.5 
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.0 
  tau: 0.5


Cora:
  lr: 0.001 
  lr_f: 0.001 
  num_hidden: 1024
  num_heads: 4  #4
  weight_decay: 0.06
  weight_decay_f: 1e-4
  max_epoch: 40
  max_epoch_f: 1000
  batch_size: 512  
  batch_size_f: 256
  num_layers: 4
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 1024 
  drop_edge_rate:  0.5 
  drop_feature_rate_1: 0.0 
  drop_feature_rate_2: 0.0 
  tau: 0.5
  


WN18RR:
  lr: 0.001 
  lr_f: 0.001 
  num_hidden: 1024
  num_heads: 4  #4
  weight_decay: 0.06
  weight_decay_f: 1e-4
  max_epoch: 40
  max_epoch_f: 1000
  batch_size: 512  
  batch_size_f: 256
  num_layers: 4
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 1024 
  drop_edge_rate:  0.5 
  drop_feature_rate_1: 0.0 
  drop_feature_rate_2: 0.0 
  tau: 0.5

FB15K237:
  lr: 0.001 
  lr_f: 0.001 
  num_hidden: 1024
  num_heads: 4  #4
  weight_decay: 0.06
  weight_decay_f: 1e-4
  max_epoch: 40
  max_epoch_f: 1000
  batch_size: 512  
  batch_size_f: 256
  num_layers: 4
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 1024 
  drop_edge_rate:  0.5 
  drop_feature_rate_1: 0.0 
  drop_feature_rate_2: 0.0 
  tau: 0.5