graphalign:
  lr_f: 0.001  
  num_hidden: 1024 
  num_heads: 4
  num_out_heads: 1
  num_layers: 4 
  weight_decay_f: 1e-4   
  max_epoch_f: 1000
  batch_size_f: 256 
  mask_rate: 0.5 
  encoder: gat  
  decoder: gat  
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 2  
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0


ogbn-arxiv:
  lr: 0.002 
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4 
  num_out_heads: 1
  weight_decay: 0.04 
  weight_decay_f: 1e-4
  max_epoch: 60  
  max_epoch_f: 1000
  batch_size: 512 #512
  batch_size_f: 256 
  mask_rate: 0.7 
  num_layers: 4 #4
  encoder: gat # gat gcn
  decoder: gat # gat gcn
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 6
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0


ogbn-products:
  lr: 0.0005 #0.0005
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4 #4
  weight_decay: 0.04
  weight_decay_f: 1e-4 #1e-4
  max_epoch: 10 
  max_epoch_f: 1000
  batch_size: 512 #512
  batch_size_f: 256
  mask_rate: 0.7 
  encoder: gat # gat gcn
  decoder: gat # gat gcn
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 1  
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0


ogbn-papers100M:
  lr: 0.001
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4 #4
  weight_decay: 0.04
  weight_decay_f: 0
  max_epoch: 10
  max_epoch_f: 1000
  batch_size: 512 #512
  batch_size_f: 256
  mask_rate: 0.5
  encoder: gat  # gat gcn
  decoder: gat  # gat gcn
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 2
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0

Wiki:
  lr: 0.001 
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 1e-4
  max_epoch: 10 
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 512
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 2
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0

FB15K237:
  lr: 0.001 
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 1e-4 
  weight_decay_f: 1e-4
  max_epoch: 1000 
  max_epoch_f: 1000
  batch_size: 256
  batch_size_f: 512
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 2
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0

ConceptNet:
  lr: 0.002
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 1e-4
  max_epoch: 30
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 512
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 6
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0
 

WN18RR:
  lr: 0.001 
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 1e-4 
  weight_decay_f: 1e-4
  max_epoch: 1000 
  max_epoch_f: 1000
  batch_size: 256
  batch_size_f: 512
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 2
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0


Cora:
  lr: 0.001 
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 1e-4 
  weight_decay_f: 1e-4
  max_epoch: 1000 
  max_epoch_f: 1000
  batch_size: 256
  batch_size_f: 512
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  optimizer: adamw
  alpha_l: 2
  scheduler: True
  residual: True
  norm: layernorm
  replace_rate: 0.0


 
